### ISSUE TITLE
RPM build script

### ISSUE THREAD

**Issue by zelid** [jhasse/mingw-docker#1]
Hello Jan Niklas,

Can you please share the mingw64-wxWidgets-static-3.1.0-20.fc25.noarch.rpm and mingw64-wxWidgets-3.1.0-20.fc25.noarch.rpm build scripts?

I want to create the similar RPM for x86 and with few custom wxWidgets builds.

Thanks,
Alex

**Comment by jhasse** [comment]
Hi! Sorry for the late response, I didn't have notifications for this repo enabled.

My script was submitted to Fedora here: https://bugzilla.redhat.com/show_bug.cgi?id=1417646
